Traceback (most recent call last):
  File "/Users/rykahsay/Library/Python/3.8/lib/python/site-packages/werkzeug/wrappers/json.py", line 119, in get_json
    rv = self.json_module.loads(data)
  File "/Users/rykahsay/Library/Python/3.8/lib/python/site-packages/flask/json/__init__.py", line 253, in loads
    return _json.loads(s, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 80)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rykahsay/projects/glygen-backend-api/api/glygen/auth.py", line 97, in post
    req_obj = request.json
  File "/Users/rykahsay/Library/Python/3.8/lib/python/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/rykahsay/Library/Python/3.8/lib/python/site-packages/werkzeug/wrappers/json.py", line 69, in json
    return self.get_json()
  File "/Users/rykahsay/Library/Python/3.8/lib/python/site-packages/werkzeug/wrappers/json.py", line 128, in get_json
    rv = self.on_json_loading_failed(e)
  File "/Users/rykahsay/Library/Python/3.8/lib/python/site-packages/flask/wrappers.py", line 25, in on_json_loading_failed
    raise BadRequest("Failed to decode JSON object: {0}".format(e))
werkzeug.exceptions.BadRequest: 400 Bad Request: Failed to decode JSON object: Expecting property name enclosed in double quotes: line 5 column 1 (char 80)
